# Site settings
email: pereirajefferson06@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:
highlighter: rouge

# SEO settings
title: Nabucodono5or
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Jefferson Abreu
profile_img: https://unsplash.it/2000/1200?image=20
profile: "Jefferson Abreu é estudante de Analise e Desenvolvimento de Sistemas no instituto Infnet,
pode ser descrito em poucas palavras: Estudante, programador, autodidata e criativo."
social:
  github: https://github.com/Nabucodono5or
  twitter: https://twitter.com/nabucodono5or
  linkedin: https://www.linkedin.com/in/jefferson-abreu-723818ba

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, rouge]
